### ISSUE TITLE
Library usage fails outside of asyncio

### ISSUE THREAD

**Issue by grischard** [jnimmo/pyIntesisHome#14]
Running this:

```python
from pyintesishome import IntesisHome
controller = IntesisHome('foo', 'bar')
```

produces the following exception:

```
Traceback (most recent call last):
  File "TestRuntimeError.py", line 2, in <module>
    controller = IntesisHome('foo', 'bar')
  File "/pyIntesisHome/pyintesishome/pyintesishome.py", line 157, in __init__
    self._eventLoop = asyncio.get_running_loop()
RuntimeError: no running event loop
```
Would it be useful to have a minimal working example with asyncio? Is anyone actually using this outside of HomeAssistant territory?

**Comment by jnimmo** [comment]
I'll get the documentation updated once I've finished making the changes (few more little things to do)

``` python
import asyncio

async def main(loop):
    controller = IntesisHome('foo', 'bar', loop=loop, device_type='airconwithme')
    await controller.connect()
    print(repr(controller.get_devices()))

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    result = loop.run_until_complete(main(loop))
```

**Comment by grischard** [comment]
All right, that worked for me! Should I simply put that example in the readme for now?

**Comment by grischard** [comment]
I've updated the readme.
