### ISSUE TITLE
Issues with fan maps

### ISSUE THREAD

**Issue by jnimmo** [jnimmo/pyIntesisHome#28]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 117, in async_setup_platform
    [
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 118, in <listcomp>
    IntesisAC(ih_device_id, device, controller)
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 179, in __init__
    self._fan_modes = controller.get_fan_speed_list(ih_device_id)
  File "/usr/local/lib/python3.8/site-packages/pyintesishome/pyintesishome.py", line 705, in get_fan_speed_list
    return list(config_fan_map.values())
AttributeError: 'int' object has no attribute 'values'
https://community.home-assistant.io/t/intesishome-wifi-ac-control/5172/317

**Comment by jnimmo** [comment]
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 117, in async_setup_platform
    [
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 118, in <listcomp>
    IntesisAC(ih_device_id, device, controller)
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 179, in __init__
    self._fan_modes = controller.get_fan_speed_list(ih_device_id)
  File "/usr/local/lib/python3.8/site-packages/pyintesishome/pyintesishome.py", line 705, in get_fan_speed_list
    return list(config_fan_map.values())
AttributeError: 'int' object has no attribute 'values'

**Comment by jnimmo** [comment]
Resolved in 1.7.6
