### ISSUE TITLE
Intesisbox issues

### ISSUE THREAD

**Issue by AAlmarwani93** [jnimmo/pyIntesisHome#49]
https://github.com/jnimmo/pyIntesisHome/blob/ea027b1d6e57a8bed689acbdeb6c5d5aed2fff0b/pyintesishome/intesisbox.py#L57

Home assistant says that there is an issue in this line which is:
```
Traceback (most recent call last):
  File "/config/custom_components/intesishome/config_flow.py", line 126, in async_step_details
    await controller.connect()
  File "/usr/local/lib/python3.10/site-packages/pyintesishome/intesisbox.py", line 57, in connect
    self._reader, self._writer = await asyncio.open_connection(
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'
```

My understanding is that you no longer can have a Loop in asyncio.open_connection.

This is breaking the integration with intesisbox.

**Comment by luismalddonado** [comment]
I have exactly the same issue
